export const USUARIOS_ACTIONS = {
    LISTAR: 'LISTAR_USUARIOS',
    OBTENER: 'OBTENER_USUARIO',
    REGISTRAR: 'REGISTRAR_USUARIO',
    ACTUALIZAR: 'ACTUALIZAR_USUARIO',
<<<<<<< HEAD
    ELIMINAR: 'ELIMINAR_USUARIO',
    REACTIVAR: 'REACTIVAR_USUARIO',
    TIPOS_USUARIO: 'OBTENER_TIPOS_USUARIO',
    ERROR: 'USUARIOS_ERROR',
    LOADING: 'USUARIOS_LOADING',
    SAVING: 'USUARIOS_SAVING',
    CLEAR_ERROR: 'USUARIOS_CLEAR_ERROR'
=======
    TIPOS_USUARIO: 'TIPOS_USUARIO',
    ERROR: 'USUARIOS_ERROR'
>>>>>>> d865f279f1327399bfaf9066fade0b791022c98d
};
