// src/context/Amenidades/ActionsTypes.js
export const AMENIDADES_ACTIONS = {
  LISTAR: "LISTAR_AMENIDADES",
  OBTENER: "OBTENER_AMENIDAD",
  REGISTRAR: "REGISTRAR_AMENIDAD",
  ACTUALIZAR: "ACTUALIZAR_AMENIDAD",
  TIPOS_AMENIDAD: "TIPOS_AMENIDAD",
  ERROR: "AMENIDADES_ERROR",
};
